# Generated by Django 4.1.2 on 2022-10-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0002_alter_familiares_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
